version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@0.0.2

jobs:

  arm-build:
    machine:
      image: ubuntu-2004:current
    environment:
      AWS_DEFAULT_OUTPUT: json
    resource_class: arm.large
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "arm-${CIRCLE_SHA1}"


workflows:
  version: 2
  deploy:
    jobs:
      - arm-build
#      - multi-arch-build
#      - upload-manifest:
#          requires:
#            - build-arm
#            - build-x86
