version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1
  aws-ecr: circleci/aws-ecr@8.1.0


jobs:
  arm-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws s3 ls
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "arm-${CIRCLE_SHA1}"

#  x86-build:
#    machine:
#      image: ubuntu-2004:current
#    resource_class: x86.medium
#    steps:
#      - checkout
#      - setup_remote_docker
#      - aws-ecr/build_and_push_image:
#          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
#          repo: "${AWS_RESOURCE_NAME_PREFIX}"
#          region: ${AWS_DEFAULT_REGION}
#          tag: "x86-${CIRCLE_SHA1}"

workflows:
  version: 2
  deploy:
    jobs:
      - arm-build
#      - x86-build