version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws s3 ls
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            aws ec2 describe-regions
      - deploy:
          name: "Upload container to registry"
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 513849602691.dkr.ecr.us-east-2.amazonaws.com
            docker build -t wtf .
            docker tag wtf:arm 513849602691.dkr.ecr.us-east-2.amazonaws.com/wtf:arm
            docker push 513849602691.dkr.ecr.us-east-2.amazonaws.com/wtf:arm

#  x86-build:
#    machine:
#      image: ubuntu-2004:current
#    resource_class: x86.medium
#    steps:
#      - checkout
#      - setup_remote_docker
#      - aws-ecr/build_and_push_image:
#          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
#          repo: "${AWS_RESOURCE_NAME_PREFIX}"
#          region: ${AWS_DEFAULT_REGION}
#          tag: "x86-${CIRCLE_SHA1}"

workflows:
  version: 2
  deploy:
    jobs:
      - arm-build
#      - x86-build