version: 2.1

jobs:

  build-x86:
    machine:
      image: cimg/node:18.4.0
    resource_class: x86.medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"


