version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:

  arm-build:
    machine:
      image: ubuntu-2004:current
    environment:
      AWS_DEFAULT_OUTPUT: json
    resource_class: arm.large
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "requirements.txt" }}
      - run:
          name: "install python3"
          command: |
            sudo apt-get install python3
      - run:
          name: Install awscli
          command: |
            python3 version
#            python3 -m venv venv
#            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export ECS_CLUSTER_NAME="${AWS_RESOURCE_NAME_PREFIX}-cluster"' >> $BASH_ENV
            echo 'export ECS_SERVICE_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"' >> $BASH_ENV
            eval $(aws ec2 describe-region)
      - deploy:
          name: "Upload container to registry"
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:arm-$CIRCLE_SHA1 .
            docker push -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$arm-CIRCLE_SHA1 .


workflows:
  version: 2
  deploy:
    jobs:
      - arm-build
#      - multi-arch-build
#      - upload-manifest:
#          requires:
#            - build-arm
#            - build-x86
